# Analysis for the counter-zero tests

**Deliver notebook, this runs with Restart Kernel and Run All Cells**

### This is to deal with MWorks skipping counter zero after code changes in ngfriedman/2310/imaginggate-laseroff 

- files in data/241111-countertest-issue[123].mwk2
- testing mwkfiles.py reader code

### references
- See mworksbehavior issue #52
- see MH LabArchives notes

# Logic of changes
- see details in MH LabArchives note, '250119: changing mwkfiles.py to deal with counter issues'

## Set up code

In [1]:
%autoreload 2

from pathlib import Path
import sys, os
from types import SimpleNamespace
import pandas as pd 

import mworksbehavior as mwb
from mworksbehavior import mwkfiles

## check to make sure the mwkfiles code is coming from the right place
# there may be better ways to do this, by forcing mwb directory to
# start of sys.path, for ex
packdir = Path('~/Repositories/mworksbehavior/mworksbehavior').expanduser()
# if this assertion fails you may need cd ~/Repositories/mworksbehavior; pip -e .
assert packdir.resolve() == Path(mwb.__path__[0]).resolve(), \
  'does not look like mworksbehavior is installed in editable form at ~/Repositories/mworksbehavior'

## Select one of the three mwk2 files here. Paul assembled a set of tests for these too in test_mwkfiles.py

In [2]:
datdir = Path('~/Repositories/mworksbehavior/mworksbehavior/tests/data').expanduser()

#mwkname = f'240918-countertest-issue1.mwk2'
mwkname = f'240918-countertest-issue2.mwk2'
#mwkname = f'241111-countertest-issue3.mwk2'

### Read the file using the plain MWF code and display the codestream for debugging

In [3]:
# Read the file using the plain MWF code
fulln = datdir / mwkname

mwf = mwkfiles.MWKFile(fulln);

In [4]:
print(mwf.firstTrStartTimeUs)
print(mwf.lastTrEndTimeUs)

262011259
330127328

In [5]:
counterIx = mwf.df.tagname.isin(['stimPySelLevel'])
#print(mwf.df.loc[counterIx,:])

In [6]:
## quick counterFIO analysis from raw stream
counterIx = mwf.df.tagname.isin(['counterFIO'])
cdf = mwf.df.loc[counterIx,:]
np.unique(np.diff(cdf.value))

array([-2244, 0, 1], dtype=object)

In [7]:
counterIx = mwf.df.tagname.isin(['counterFIO','strobedDigitalWord', 'stimPySelLevel'])
pd.set_option('display.max_rows', 60)
pd.set_option('display.min_rows', 50)


mwf.df.loc[counterIx,:]

                 tagname     timeUs value  timeFmStUs
159       stimPySelLevel  260282108     2         129
197   strobedDigitalWord  260282124     4         145
199           counterFIO  260282124  2245         145
363       stimPySelLevel  260284031     2        2052
401           counterFIO  260284135  2245        2156
402   strobedDigitalWord  260284136     4        2157
574       stimPySelLevel  262000699     2     1718720
612           counterFIO  262000750  2245     1718771
613   strobedDigitalWord  262000750     4     1718771
637   strobedDigitalWord  262009570     0     1727591
649   strobedDigitalWord  262011259   170     1729280
650           counterFIO  262011346     1     1729367
652   strobedDigitalWord  262011799   170     1729820
654   strobedDigitalWord  262012280   170     1730301
659   strobedDigitalWord  262012753   200     1730774
661   strobedDigitalWord  262013199     0     1731220
663   strobedDigitalWord  262013639     0     1731660
665   strobedDigitalWord  262014109   262     1732130
667   strobedDigitalWord  262014584    12     1732605
669   strobedDigitalWord  262015064   201     1733085
691   strobedDigitalWord  262016140     6     1734161
693       stimPySelLevel  262016905     2     1734926
1040          counterFIO  266196329     2     5914350
1043          counterFIO  266226330     3     5944351
1046          counterFIO  266261316     4     5979337
...                  ...        ...   ...         ...
8726          counterFIO  329826414  1911    69544435
8729          counterFIO  329861334  1912    69579355
8732          counterFIO  329896328  1913    69614349
8735          counterFIO  329926334  1914    69644355
8738          counterFIO  329961313  1915    69679334
8741          counterFIO  329996317  1916    69714338
8744          counterFIO  330026332  1917    69744353
8747          counterFIO  330061329  1918    69779350
8750          counterFIO  330096412  1919    69814433
8753          counterFIO  330126320  1920    69844341
8775  strobedDigitalWord  330126400    85    69844421
8777  strobedDigitalWord  330126883    85    69844904
8779  strobedDigitalWord  330127328    85    69845349
8794  strobedDigitalWord  330127834   170    69845855
8797  strobedDigitalWord  330128279   170    69846300
8799  strobedDigitalWord  330128743   170    69846764
8804  strobedDigitalWord  330129224   200    69847245
8806  strobedDigitalWord  330129766     0    69847787
8809  strobedDigitalWord  330130274     0    69848295
8811  strobedDigitalWord  330130730   330    69848751
8813  strobedDigitalWord  330131201   129    69849222
8815  strobedDigitalWord  330131926   201    69849947
8837  strobedDigitalWord  330132938     6    69850959
8839      stimPySelLevel  330133545     6    69851566
8937          counterFIO  330161478  1921    69879499

[2081 rows x 4 columns]

## Test with the full mwkfiles.RetinotopyMap2Stim / CounterStimMixin parsing code

In [8]:
mwf = mwkfiles.RetinotopyMap2StimMWKFile(fulln,doTryFixCorrupt=True)
mwf.compute_imaging_constants()
print(mwf.nstim, mwf.nframes_stim)
assert mwf.nstim * mwf.nframes_stim == 1920

8 240

/Users/histed/Repositories/mworksbehavior/mworksbehavior/mwkfiles.py:378: UserWarning: Found first counter tick to be 1, expected zero; subtracting 1 from all counter vals, altering df values
  warnings.warn(f"Found first counter tick to be 1, expected zero; subtracting 1 from all counter vals, altering df values")
/Users/histed/Repositories/mworksbehavior/mworksbehavior/mwkfiles.py:470: UserWarning: Trying to fix file: Number of frames is one less than expected, probably first trial is short, be careful w/ analysis
  warnings.warn('Trying to fix file: Number of frames is one less than expected, probably first trial is short, be careful w/ analysis')

In [9]:
display(mwf.counterStats)

namespace(nCounterTicks=1919, nTotalStims=8, ticksPerStim=239.875)

In [10]:
display(mwf.firstCounterUs)
display(mwf.firstTrStartTimeUs)
display(mwf.firstTrEndTimeUs)
display(mwf.constS)

tdf = mwf.get_codedf(mwf.counterVar)
#display(tdf)

display(mwf.stimDf)

counterStatN = SimpleNamespace(minCounterVal=min(tdf.value),
                               maxCounterVal=max(tdf.value), 
                               nTotalStim=len(mwf.stimDf),
                               nUniqueStim=mwf.nstim)
ctSN = counterStatN
ctSN.counterRange = ctSN.maxCounterVal - ctSN.minCounterVal + 2 # count at both ends
ctSN.counterTickPerStim = ctSN.counterRange/ctSN.nTotalStim
display(ctSN)

0    266196329
Name: timeUs, dtype: int64

262011259

274126555

counterNPre      60
counterNPost    120
counterNStim     60
dtype: int64

,stimPySelLevel,tStim1AzimuthDeg,tStim2AzimuthDeg,tStim1ElevationDeg,tStim2ElevationDeg,tStim1GratingSpeedDps,tStim2GratingSpeedDps,tStim1GratingSpatialFreqCpd,tStim2GratingSpatialFreqCpd,tStim1OriNoiseF0Cpd,...,tATrainNPulses,tBTrainNPulses,tATrainPulseLengthMs,tBTrainPulseLengthMs,tARampLengthMs,tBRampLengthMs,tARampExtraConstantLengthMs,tBRampExtraConstantLengthMs,tAStartOffsetMs,tBStartOffsetMs
0,2,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
1,5,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
2,6,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
3,7,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
4,0,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
5,4,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
6,3,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
7,1,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0

namespace(minCounterVal=1,
          maxCounterVal=1919,
          nTotalStim=8,
          nUniqueStim=8,
          counterRange=1920,
          counterTickPerStim=240.0)