# Analysis for the counter-zero tests

- files in data/241111-countertest-issue[123].mwk2
- testing mwkfiles.py reader code

## This file shows the missing counter tick on first trial

### references
- see MH LabArchives notes

In [1]:
%autoreload 2

from pathlib import Path
import sys, os
from types import SimpleNamespace
import pandas as pd 

import mworksbehavior as mwb
from mworksbehavior import mwkfiles

## check to make sure the mwkfiles code is coming from the right place
# there may be better ways to do this, by forcing mwb directory to
# start of sys.path, for ex
packdir = Path('~/Repositories/mworksbehavior/mworksbehavior').expanduser()
# if this assertion fails you may need cd ~/Repositories/mworksbehavior; pip -e .
assert packdir.resolve() == Path(mwb.__path__[0]).resolve(), \
  'does not look like mworksbehavior is installed in editable form at ~/Repositories/mworksbehavior'

In [2]:
datdir = Path('~/Repositories/mworksbehavior/mworksbehavior/tests/data').expanduser()

#mwkname = f'240918-countertest-issue1.mwk2'
mwkname = f'240918-countertest-issue2.mwk2'
#mwkname = f'241111-countertest-issue3.mwk2'

### Read the file using the plain MWF code and display the codestream for debugging

In [3]:
# Read the file using the plain MWF code
fulln = datdir / mwkname

mwf = mwkfiles.MWKFile(fulln);

## Here you can see the first trial has one fewer counter tick

Below code parses out the counter ticks by trials. The first trial has counter=1, then a looong delay, then counter == 2. That counter = 1 gets counted as one of the 240 counter ticks for that trial.

In [28]:
pd.set_option('display.min_rows', 10)

cdf = mwf.get_codedf('strobedDigitalWord', value=170)
trStartsUs = cdf.timeUs[0::3].to_numpy()
cdf = mwf.get_codedf('strobedDigitalWord', value=85)
trEndsUs = cdf.timeUs[0::3].to_numpy()

cdf = mwf.get_codedf('counterFIO')
ctL = [None]*len(trStartsUs)
for (iS,st) in enumerate(trStartsUs):
    tCounter = cdf.loc[(cdf.timeUs >= trStartsUs[iS]) & (cdf.timeUs < trEndsUs[iS]),:]
    ctL[iS] = tCounter

print('Trial 0')    
display(ctL[0])
print('Trial 1')
display(ctL[1])

Trial 0

     df_index     timeUs value  timeFmStUs  timeDiffUs
0         650  262011346     1     1729367         NaN
1        1040  266196329     2     5914350   4184983.0
2        1043  266226330     3     5944351     30001.0
3        1046  266261316     4     5979337     34986.0
4        1049  266296318     5     6014339     35002.0
..        ...        ...   ...         ...         ...
235      1824  273996379   236    13714400     35018.0
236      1827  274026332   237    13744353     29953.0
237      1830  274061315   238    13779336     34983.0
238      1833  274096334   239    13814355     35019.0
239      1836  274126328   240    13844349     29994.0

[240 rows x 5 columns]

Trial 1

     df_index     timeUs value  timeFmStUs  timeDiffUs
240      2020  274161314   241    13879335     34986.0
241      2023  274196456   242    13914477     35142.0
242      2026  274226318   243    13944339     29862.0
243      2029  274261404   244    13979425     35086.0
244      2032  274296317   245    14014338     34913.0
..        ...        ...   ...         ...         ...
475      2807  281996332   476    21714353     35008.0
476      2810  282026316   477    21744337     29984.0
477      2813  282061334   478    21779355     35018.0
478      2816  282096337   479    21814358     35003.0
479      2819  282126338   480    21844359     30001.0

[240 rows x 5 columns]